version: '2'

services:
    ingress:
        image: traefik:1.3-alpine
        command: --docker
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - traefik
            - default

    dashboard_web:
        extends:
            file: docker/templates.yml
            service: web
        depends_on:
            - dashboard_php
        environment:
            - SERVER_NAME=dashboard.localhost
            - PHP_BACKEND=dashboard_php
            - ROOT=/opt/src/Dashboard/public
        labels:
            - "traefik.backend=dashboard_web"
            - "traefik.frontend.rule=Host:dashboard.localhost"

    dashboard_php:
        extends:
            file: docker/templates.yml
            service: php-fpm
        depends_on:
            - catalog_web
            - purchase_web
            - sales_web

    catalog_web:
        extends:
            file: docker/templates.yml
            service: web
        depends_on:
            - catalog_php
        environment:
            - SERVER_NAME=catalog.localhost
            - PHP_BACKEND=catalog_php
            - ROOT=/opt/src/Catalog/public
        labels:
            - "traefik.backend=catalog_web"
            - "traefik.frontend.rule=Host:catalog.localhost"

    catalog_php:
        extends:
            file: docker/templates.yml
            service: php-fpm
        volumes:
            - ./:/opt:cached

    sales_web:
        extends:
            file: docker/templates.yml
            service: web
        depends_on:
            - sales_php
        environment:
            - SERVER_NAME=sales.localhost
            - PHP_BACKEND=sales_php
            - ROOT=/opt/src/Sales/public
        labels:
            - "traefik.backend=sales_web"
            - "traefik.frontend.rule=Host:sales.localhost"

    sales_php:
        extends:
            file: docker/templates.yml
            service: php-fpm

    purchase_web:
        extends:
            file: docker/templates.yml
            service: web
        depends_on:
            - purchase_php
        environment:
            - SERVER_NAME=purchase.localhost
            - PHP_BACKEND=purchase_php
            - ROOT=/opt/src/Purchase/public
        labels:
            - "traefik.backend=purchase_web"
            - "traefik.frontend.rule=Host:purchase.localhost"

    purchase_php:
        extends:
            file: docker/templates.yml
            service: php-fpm

    stock_web:
        extends:
            file: docker/templates.yml
            service: web
        depends_on:
            - stock_php
        environment:
            - SERVER_NAME=stock.localhost
            - PHP_BACKEND=stock_php
            - ROOT=/opt/src/Stock/public
        labels:
            - "traefik.backend=stock_web"
            - "traefik.frontend.rule=Host:stock.localhost"

    stock_php:
        extends:
            file: docker/templates.yml
            service: php-fpm

    test:
        image: matthiasnoback/building_autonomous_services_php_cli
        env_file: docker/.env
        user: ${HOST_UID}:${HOST_GID}
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_NAME_OR_IP}"
        volumes:
            - ${PWD}:/opt:cached
        network_mode: host
        command: "true" # do nothing when started by `docker-compose up`
